In [7]:
!pip install mediapipe

Requirement already satisfied: mediapipe in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (0.10.21)
Requirement already satisfied: absl-py in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (2.1.0)
Requirement already satisfied: attrs>=19.1.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (25.1.0)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (25.2.10)
Requirement already satisfied: jax in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (0.5.2)
Requirement already satisfied: jaxlib in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (0.5.1)
Requirement already satisfied: matplotlib in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (3.10.1)
Requirement already satisfied: numpy<2 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (1.26.4)
Requirement already satisfied: opencv-contrib-python in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (4.11.0.86)
Requirement already satisfied: protobuf<5,>=4.25.3 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (4.25.6)
Requirement already satisfied: sounddevice>=0.4.4 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (0.5.1)
Requirement already satisfied: sentencepiece in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from mediapipe) (0.2.0)
Requirement already satisfied: CFFI>=1.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from sounddevice>=0.4.4->mediapipe) (1.17.1)
Requirement already satisfied: ml_dtypes>=0.4.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jax->mediapipe) (0.5.1)
Requirement already satisfied: opt_einsum in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jax->mediapipe) (3.4.0)
Requirement already satisfied: scipy>=1.11.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from jax->mediapipe) (1.14.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->mediapipe) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->mediapipe) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->mediapipe) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->mediapipe) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->mediapipe) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->mediapipe) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->mediapipe) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->mediapipe) (2.9.0.post0)
Requirement already satisfied: pycparser in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from CFFI>=1.0->sounddevice>=0.4.4->mediapipe) (2.22)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib->mediapipe) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: C:\Users\Hp\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [10]:
import mediapipe as mp
import cv2

ModuleNotFoundError: No module named 'mediapipe'

In [9]:
mp_drawing = mp.solutions.drawing_utils
mp_holistic = mp.solutions.holistic
mp_face_mesh = mp.solutions.face_mesh

NameError: name 'mp' is not defined

In [55]:
cap = cv2.VideoCapture(0)
# Initiate holistic model
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    while cap.isOpened():
        ret, frame = cap.read()
        
        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
        # Make Detections
        results = holistic.process(image)
        # print(results.face_landmarks)
        
        # face_landmarks, pose_landmarks, left_hand_landmarks, right_hand_landmarks
        
        # Recolor image back to BGR for rendering
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        
        # 1. Draw face landmarks
        mp_drawing.draw_landmarks(image, results.face_landmarks, mp_face_mesh.FACEMESH_TESSELATION, 
                                 mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1),
                                 mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                                 )
        
        # 2. Right hand
        mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                                 )

        # 3. Left Hand
        mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                                 )

        # 4. Pose Detections
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                                 )
                        
        cv2.imshow('Raw Webcam Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()
#results.pose_landmarks

In [57]:
import csv 
import os 
import numpy as np

In [59]:
num_coords = len(results.pose_landmarks.landmark)+len(results.face_landmarks.landmark)

In [61]:
landmarks = ['class']
for val in range (1, num_coords+1):
    landmarks += ['x{}'.format(val), 'y{}'.format(val), 'z{}'.format(val), 'v{}'.format(val)]

In [63]:
with open ('coords.csv', mode='w', newline='') as f:
    csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
    csv_writer.writerow(landmarks)

In [69]:
class_name = "rising left hand "

In [71]:
cap = cv2.VideoCapture(0)
# Initiate holistic model
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    while cap.isOpened():
        ret, frame = cap.read()
        
        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
        # Make Detections
        results = holistic.process(image)
        # print(results.face_landmarks)
        
        # face_landmarks, pose_landmarks, left_hand_landmarks, right_hand_landmarks
        
        # Recolor image back to BGR for rendering
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        
        # 1. Draw face landmarks
        mp_drawing.draw_landmarks(image, results.face_landmarks, mp_face_mesh.FACEMESH_TESSELATION, 
                                 mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1),
                                 mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                                 )
        
        # 2. Right hand
        mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                                 )

        # 3. Left Hand
        mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                                 )

        # 4. Pose Detections
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                                 )
        try:
            pose = results.pose_landmarks.landmark
            pose_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in pose ]).flatten())
            
            face = results.face_landmarks.landmark
            face_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in face]).flatten())

            row = pose_row+face_row
            row.insert(0, class_name)

            with open ('coords.csv', mode='a', newline='') as f:
                csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
                csv_writer.writerow(row)
                
        except:
            pass
                        
        cv2.imshow('Raw Webcam Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

In [73]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [75]:
df = pd.read_csv('coords.csv')

In [77]:
df.head()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z499,v499,x500,y500,z500,v500,x501,y501,z501,v501
0,rising right hand,0.553240,0.109252,-0.760186,0.999876,0.579272,0.051218,-0.729375,0.999838,0.599647,...,0.002386,0.0,0.632689,0.037668,0.019316,0.0,0.636539,0.032523,0.020093,0.0
1,rising right hand,0.552209,0.115756,-0.702105,0.999879,0.579267,0.051569,-0.673380,0.999840,0.599473,...,0.000655,0.0,0.623595,0.058037,0.016104,0.0,0.627437,0.052753,0.016767,0.0
2,rising right hand,0.545596,0.131715,-0.677569,0.999887,0.572320,0.066817,-0.645375,0.999851,0.591453,...,-0.001592,0.0,0.619456,0.083992,0.012531,0.0,0.623198,0.079621,0.013038,0.0
3,rising right hand,0.539901,0.149465,-0.642141,0.999888,0.569994,0.083442,-0.607730,0.999851,0.588448,...,-0.002530,0.0,0.617135,0.089504,0.011564,0.0,0.620994,0.086467,0.011780,0.0
4,rising right hand,0.535229,0.165325,-0.621157,0.999886,0.558728,0.103515,-0.597759,0.999847,0.582526,...,-0.000232,0.0,0.620830,0.104708,0.015737,0.0,0.624639,0.100860,0.016325,0.0

In [79]:
df.tail()

,class,x1,y1,z1,v1,x2,y2,z2,v2,x3,...,z499,v499,x500,y500,z500,v500,x501,y501,z501,v501
97,rising left hand,0.480229,0.465581,-0.530173,0.999953,0.494438,0.437080,-0.472954,0.999891,0.503046,...,0.000524,0.0,0.505753,0.427177,0.010760,0.0,0.507833,0.425556,0.011150,0.0
98,rising left hand,0.481994,0.459276,-0.512905,0.999953,0.495937,0.430202,-0.453001,0.999892,0.504375,...,0.001298,0.0,0.506237,0.415697,0.012627,0.0,0.508438,0.413637,0.013112,0.0
99,rising left hand,0.482239,0.428768,-0.433516,0.999954,0.496933,0.393747,-0.383476,0.999891,0.505264,...,0.002155,0.0,0.502288,0.371298,0.015568,0.0,0.504417,0.369250,0.016183,0.0
100,rising left hand,0.480668,0.380790,-0.415356,0.999958,0.495905,0.340840,-0.361518,0.999900,0.504421,...,0.003135,0.0,0.501259,0.322906,0.019197,0.0,0.503613,0.320070,0.020124,0.0
101,rising left hand,0.488355,0.330453,-0.434089,0.999957,0.498951,0.288802,-0.380340,0.999899,0.506756,...,0.001201,0.0,0.507878,0.272475,0.017993,0.0,0.510718,0.269445,0.018931,0.0

In [81]:
x = df.drop('class', axis=1)
y = df['class']

In [83]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state=1234)

In [85]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import  StandardScaler
from sklearn.linear_model import LogisticRegression, RidgeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [87]:
pipelines = {
    'lr':make_pipeline(StandardScaler(), LogisticRegression()), 
    'rc':make_pipeline(StandardScaler(), RidgeClassifier()), 
    'rf':make_pipeline(StandardScaler(), RandomForestClassifier()), 
    'gb':make_pipeline(StandardScaler(), GradientBoostingClassifier())
}

In [89]:
fit_models = {}
for algo, pipeline in pipelines.items():
    model= pipeline.fit(x_train, y_train)
    fit_models[algo] = model

In [91]:
fit_models

{'lr': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('logisticregression', LogisticRegression())]),
 'rc': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('ridgeclassifier', RidgeClassifier())]),
 'rf': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('randomforestclassifier', RandomForestClassifier())]),
 'gb': Pipeline(steps=[('standardscaler', StandardScaler()),
                 ('gradientboostingclassifier', GradientBoostingClassifier())])}

In [93]:
fit_models['rc'].predict(x_test)

array(['rising left hand ', 'rising right hand ', 'rising right hand ',
       'rising right hand ', 'rising right hand ', 'rising right hand ',
       'rising right hand ', 'rising left hand ', 'rising right hand ',
       'rising right hand ', 'rising right hand ', 'rising right hand ',
       'rising left hand ', 'rising right hand ', 'rising left hand ',
       'rising left hand ', 'rising right hand ', 'rising right hand ',
       'rising right hand ', 'rising left hand ', 'rising right hand ',
       'rising right hand ', 'rising right hand ', 'rising left hand ',
       'rising right hand ', 'rising left hand ', 'rising left hand ',
       'rising left hand ', 'rising right hand ', 'rising right hand ',
       'rising left hand '], dtype='<U18')

In [95]:
from sklearn.metrics import accuracy_score # Accuracy metrics 
import pickle

In [97]:
for algo, model in fit_models.items():
    yhat = model.predict(x_test)
    print(algo, accuracy_score(y_test, yhat))

lr 1.0
rc 1.0
rf 1.0
gb 1.0

In [107]:
with open('body_language.pkl', 'wb') as f:
    pickle.dump(fit_models['rf'], f)

In [109]:
with open('body_language.pkl', 'rb') as f:
    model = pickle.load(f)

In [111]:
model

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestclassifier', RandomForestClassifier())])

In [ ]:
cap = cv2.VideoCapture(0)
# Initiate holistic model
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    while cap.isOpened():
        ret, frame = cap.read()
        
        # Recolor Feed
        image = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        image.flags.writeable = False
        # Make Detections
        results = holistic.process(image)
        # print(results.face_landmarks)
        
        # face_landmarks, pose_landmarks, left_hand_landmarks, right_hand_landmarks
        
        # Recolor image back to BGR for rendering
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        
        # 1. Draw face landmarks
        mp_drawing.draw_landmarks(image, results.face_landmarks, mp_face_mesh.FACEMESH_TESSELATION, 
                                 mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1),
                                 mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                                 )
        
        # 2. Right hand
        mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
                                 )

        # 3. Left Hand
        mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                                 )

        # 4. Pose Detections
        mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS, 
                                 mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4),
                                 mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                                 )
        
        try:
            # Extract Pose landmarks
            pose = results.pose_landmarks.landmark
            pose_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in pose]).flatten())
            
            # Extract Face landmarks
            face = results.face_landmarks.landmark
            face_row = list(np.array([[landmark.x, landmark.y, landmark.z, landmark.visibility] for landmark in face]).flatten())
            
            # Concate rows
            row = pose_row+face_row
            
#             # Append class name 
#             row.insert(0, class_name)
            
#             # Export to CSV
#             with open('coords.csv', mode='a', newline='') as f:
#                 csv_writer = csv.writer(f, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
#                 csv_writer.writerow(row) 

            # Make Detections
            X = pd.DataFrame([row])
            body_language_class = model.predict(X)[0]
            body_language_prob = model.predict_proba(X)[0]
            print(body_language_class, body_language_prob)
            
            # Grab ear coords
            coords = tuple(np.multiply(
                            np.array(
                                (results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].x, 
                                 results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].y))
                        , [640,480]).astype(int))
            
            cv2.rectangle(image, 
                          (coords[0], coords[1]+5), 
                          (coords[0]+len(body_language_class)*20, coords[1]-30), 
                          (245, 117, 16), -1)
            cv2.putText(image, body_language_class, coords, 
                        cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
            
            # Get status box
            cv2.rectangle(image, (0,0), (250, 60), (245, 117, 16), -1)
            
            # Display Class
            cv2.putText(image, 'CLASS'
                        , (95,12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
            cv2.putText(image, body_language_class.split(' ')[0]
                        , (90,40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
            
            # Display Probability
            cv2.putText(image, 'PROB'
                        , (15,12), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 0), 1, cv2.LINE_AA)
            cv2.putText(image, str(round(body_language_prob[np.argmax(body_language_prob)],2))
                        , (10,40), cv2.FONT_HERSHEY_SIMPLEX, 1, (255, 255, 255), 2, cv2.LINE_AA)
            
        except:
            pass
                        
        cv2.imshow('Raw Webcam Feed', image)

        if cv2.waitKey(10) & 0xFF == ord('q'):
            break

cap.release()
cv2.destroyAllWindows()

In [ ]:
tuple(np.multiply(np.array((results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].x, 
results.pose_landmarks.landmark[mp_holistic.PoseLandmark.LEFT_EAR].y)), [640,480]).astype(int))